// MP1: Warm up
// Course: CSS290, Fall 2025
// Author: Kelvin Sung
// Program:
//      Write a program that allows the user to enter a number of quarters, 
//      dimes, and nickels and then outputs the monetary value of the coins 
//      in cents. For example, if the user enters 2 for the number of quarters, 
//      3 for the number of dimes, and 1 for the number of nickels, then the 
//      program should output that the coins are worth 85 cents.

// The following solution is generated by the GitHub's VSC Copilot tool. 
// I modified the code in the following ways:
//    1. Added comments to explain the code.
//    2. Used constants for coin values to improve readability.
//    3. Improved formatting of output for better readability.

#include <iostream>
using namespace std;

// constants
const int QUARTER_VALUE = 25;
const int DIME_VALUE = 10;
const int NICKEL_VALUE = 5;

int main() {
    int quarters, dimes, nickels;  // variables to hold user input number of respective coins
    cout << "Please enter 3 numbers (quarters dimes and nickels): ";

    cin >> quarters >> dimes >> nickels; // read and verify user input 
    cout << "You entered: quarters(" << quarters << "), dimes(" 
         << dimes << "), and nickels(" << nickels << ")" << endl;  // Avoid line wrapping for readability

    // compute the actual cents and echo the result
    int totalCents = (quarters * QUARTER_VALUE) + (dimes * DIME_VALUE) + (nickels * NICKEL_VALUE);
    cout << "The total value of the coins is: " << totalCents << " cents." << endl;

    return 0;
}
    
